apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post-container
        image: adarshbinomon/echoblog-backend-post-service

---
apiVersion: v1
kind: Service
metadata: 
  name: post-service
spec:
  selector:
    app: post
  ports: 
    - name: post
      protocol: TCP
      port: 4002
      targetPort: 4002